version: "1.0"
info:
  model: int-scaffold
packages:
- name: SirfPro3Project
  gitServerName: sirfpro
  gitUrl: https://github.com/sirf786/SirfPro3Project
  gitUsername: sirf786
  gitBranch: main
services:
- serviceName: project.sirfpro3.integrations:Test1
  packages:
  - name: SirfPro3Project
    version: "1.0"
